@apim = https://contosoapim4-local.azure-api.net
@func = http://localhost:7071

### Invalid user
POST {{apim}}/users HTTP/1.1
Content-type: application/json

{
  "id": 1,
  "name": "Doe",
  "address": {
    "postalCode": "11111"
  }
}

### Valid user
POST {{apim}}/users HTTP/1.1
Content-type: application/json

{
  "id": 1,
  "name": "Doe",
  "address": {
    "postalCode": "12345"
  }
}

### Get products
GET {{apim}}/products HTTP/1.1
Content-type: application/json

### Get csv data using map
POST {{func}}/api/csv HTTP/1.1
Content-type: application/json

{
  "csv": "https://mylogicapps9000.blob.core.windows.net/files/data.csv",
  "map": "https://mylogicapps9000.blob.core.windows.net/files/data_map.json"
}